### PR TITLE
added more chess opening book

### PR DESCRIPTION
**Pull request by prasoonmhwr**
- https://github.com/hrushikeshrv/chessengine/issues/11

@hrushikeshrv Please let me know if this is what you were looking for or you need any changes :)

### CODE REVIEW

**Comment by hrushikeshrv** [comment]
Hi @prasoonmhwr, thanks for the PR. How many games in total have you included in this new set of PGN files?

**Comment by prasoonmhwr** [comment]
> Hi @prasoonmhwr, thanks for the PR. How many games in total have you included in this new set of PGN files?

@hrushikeshrv  On an average 10000 games per file

**Comment by prasoonmhwr** [comment]
> > Hi @prasoonmhwr, thanks for the PR. How many games in total have you included in this new set of PGN files?
> 
> @hrushikeshrv On an average 10000 games per file

@hrushikeshrv Is it enough?

**Comment by hrushikeshrv** [comment]
Hey, sorry for the late response. I checked the PGN files you have added, and it looks like all of them contain the Modern Queen opening. Can you try including PGN files from different opening styles?

**Comment by prasoonmhwr** [comment]
> Hey, sorry for the late response. I checked the PGN files you have added, and it looks like all of them contain the Modern Queen opening. Can you try including PGN files from different opening styles?

@hrushikeshrv please check now

**Comment by hrushikeshrv** [comment]
Looks better now. I'll choose a subset of these files to include into the package 👍🏻

**Pull request closed without merging**
